apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bedrock-connect.fullname" . }}
  labels:
    {{- include "bedrock-connect.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bedrock-connect.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "bedrock-connect.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bedrock-connect.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            - "java"
            - "-Xms1G"
            - "-Xmx1G"
            - "-jar"
            - "BedrockConnect-1.0-SNAPSHOT.jar"
            - "nodb=true"
            {{- if .Values.bedrockConnect.whitelistUsers }}
            - "whitelist=/whitelist.txt"
            {{- end }}
            - "featured_servers={{ .Values.bedrockConnect.featuredServers }}"
            {{- if .Values.bedrockConnect.customServers }}
            - "custom_servers=/custom_servers.json"
            {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: bedrock
              containerPort: 19132
              protocol: UDP
          volumeMounts:
            - name: config-volume
              mountPath: /custom_servers.json
              subPath: custom_servers.json
            - name: config-volume
              mountPath: /whitelist.txt
              subPath: whitelist.txt
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "bedrock-connect.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
